title: "Welcome to my blog! – BessyHuang"
description: > # this means to ignore newlines until "baseurl:"
  我是一個主修圖資系，同時雙主修統資系的大學生。
  喜歡吸收新知、拉小提琴…各種陶冶性情的休閒活動我都愛，
  或是接受一些具有挑戰性且富有意義的事。
permalink: ':title/'
baseurl: "/BLOG-FlexibleJekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Huang, Feng-Chia # add your name
author-img: my_photo_100x120.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: 黃丰嘉 # add your Facebook handle
social-github: bessyhuang # add your Github handle
social-linkedin: Feng-Chia Huang # add your Linkedin handle
social-email: bessyhuang1@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
